### ISSUE TITLE
🐞 [BUG]: README points to broken Wiki link

### ISSUE THREAD

**Issue by Gumnos** [bilbilak/godini#1]
### Version

0.1.0

### What's the problem?

In the `README.md` file, it links to https://github.com/bilbilak/godini/wiki for the wiki, but attempting to click that link just redirects back to https://github.com/bilbilak/godini

Is there something that needs to be configured to make the Wiki publicly visible? Or a different URL?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 4r7if3x** [comment]
Thanks for your report. I still need to add documentation to the Wiki, which is currently empty. I suspect that's why you're being redirected. Interestingly, I haven't encountered this behavior on my browser, so it might also be related to server caching.

I'll update the Wiki soon to avoid this in the future...

**Comment by Gumnos** [comment]
Using FF as my browser here, in case that matters in tracking down the difference.

**Comment by 4r7if3x** [comment]
The issue is resolved once I created the first Wiki page that initiated its repository. I'll gradually add more usage instructions there.
